### PR TITLE
Fix a typo in the query label for the distributionbylayer metric

### PR DESCRIPTION
**Pull request by mprahl**

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]
Thanks!

**Comment by mprahl** [comment]
@ldelossa thanks for the review! Could you please approve the workflow? I had to reformat the commit message for the "Commit Check" check.

**Comment by ldelossa** [comment]
Commit needs to be signed off.

**Comment by mprahl** [comment]
@ldelossa thanks! I adjusted the commit message to have a sign off now.

**Review by ldelossa — APPROVED** [review]

**Pull request merged**
