### PR TITLE
Release "quay.io/projectquay/golang" Docker Image for Linux/ARM64

### PR DESCRIPTION
**Pull request by odidev**
Added platform check in the Dockerfile to download GO binary according to the host platform, and added buildx utility to the golang-image.yml file to release golang for both AMD64 and ARM64.

Signed-off-by: odidev <odidev@puresoftware.com>

### CODE REVIEW

**Review by hdonnay — DISMISSED** [review]
LGTM

Needs a rebase (or I can do it) and Github Actions needs to come back from the dead and run the tests.

**Comment by odidev** [comment]
@hdonnay,  I have rebased this PR.

**Review by hdonnay — APPROVED** [review]

**Comment by odidev** [comment]
@hdonnay, Thanks for merging this PR. May I know when are you planning to release the docker image for Linux/ARM64?

**Comment by hdonnay** [comment]
@odidev Looks like the 1.17 version has both arm64 and amd64 building now. There was a corner case in the "latest versions" script that's fixed.

**Pull request merged**
