### PR TITLE
feature: added ppc64le support to golang base image

### PR DESCRIPTION
**Pull request by mayurwaghmode**
This PR will add ppc64le support to the [quay.io/projectquay/golang](quay.io/projectquay/golang) image.

### CODE REVIEW

**Comment by mayurwaghmode** [comment]
@crozzy can u take a look at this PR?

**Comment by hdonnay** [comment]
This is an easy enough change, but to what end? Our sqlite dependency [doesn't build on `ppc64le`](https://modern-c.appspot.com/-/builder/?importpath=modernc.org%2fsqlite).

**Comment by crozzy** [comment]
I think if the aim, as it was stated, is just to produce a `ppc64le` golang base image, and not to add the support to Clair (which as stated isn't currently possible), the Claircore repo isn't the right place to do it. Down the road this workflow is likely to change and creating tangential dependencies doesn't seem wise.

**Comment by mayurwaghmode** [comment]
> This is an easy enough change, but to what end? Our sqlite dependency [doesn't build on `ppc64le`](https://modern-c.appspot.com/-/builder/?importpath=modernc.org%2fsqlite).

@hdonnay now sqlite dependency has started [getting built on 'ppc64le' architecture](https://modern-c.appspot.com/-/builder/?importpath=modernc.org%2fsqlite) as well

**Comment by hdonnay** [comment]
And to be clear, this is because you want Clair to support `ppc64le`?

**Comment by crozzy** [comment]
Now there is a path, this seems valid again, please could you rebase and this is a nit but can you amend the commit message to start with `chore:` as opposed to `feature:`, thanks @mayurwaghmode !

**Comment by mayurwaghmode** [comment]
> Now there is a path, this seems valid again, please could you rebase and this is a nit but can you amend the commit message to start with `chore:` as opposed to `feature:`, thanks @mayurwaghmode !

@crozzy Done!

**Pull request merged**
