### PR TITLE
all: various whiteout file support updates

### PR DESCRIPTION
**Pull request by RTann**

### CODE REVIEW

**Comment by RTann** [comment]
can someone remind me how these test cases were written because there is no chance i'm manually updating these

**Review by crozzy — COMMENTED** [review]
The package scanner versions should probably be update here

**Comment by RTann** [comment]
> The package scanner versions should probably be update here

I always forget that, thanks

**Review by crozzy — APPROVED** [review]
LGTM

**Comment by RTann** [comment]
sorry @crozzy I will need one more review. I realized I forgot the log discard stuff in the python packagescanner, so I fixed that, and I also updated it to match what Ruby does to avoid future mishaps

**Review by crozzy — APPROVED** [review]

**Pull request merged**
