### PR TITLE
periodic: add additional search patterns

### PR DESCRIPTION
**Pull request by hdonnay**
This adds a layer of hierarchy to the tests to allow for adding more patterns.

See-also: PROJQUAY-5293

### CODE REVIEW

**Comment by hdonnay** [comment]
Blocked on [STONEBLD-1472](https://issues.redhat.com/projects/STONEBLD/issues/STONEBLD-1472).

**Comment by hdonnay** [comment]
Added a workaround in the form of just ignoring the `Module` member, which feels bad.

**Comment by hdonnay** [comment]
It seems more likely that Red Hat will publish SPDX manifests before it fixes this metadata hole, so I'd like to merge this with the module ignore hack.

**Review by crozzy — APPROVED** [review]

**Comment by hdonnay** [comment]
Will merge with green CI. Enabling the periodic tests passes on my local machine:
```
% git log -1 HEAD; go test -run RPMSpotCheck ./test/periodic -enable
commit e4d321e1234886f3a4e33347bc34edaf6855dd3f (HEAD -> hack/rpm-spotcheck, fork/hack/rpm-spotcheck)
Author: Hank Donnay <hdonnay@redhat.com>
Date:   Mon Apr 10 19:25:53 2023 -0500

    periodic: add additional search patterns
    
    This adds a layer of hierarchy to the tests to allow for adding more
    patterns.
    
    See-also: PROJQUAY-5293
    See-also: STONEBLD-1472
    Signed-off-by: Hank Donnay <hdonnay@redhat.com>
ok  	github.com/quay/claircore/test/periodic	7.021s
```

**Pull request merged**
