### PR TITLE
gobin: reduce some log chatter

### PR DESCRIPTION
**Pull request by hdonnay**
Spotted when running across the quayio corpus. These changes should pollute the warning logs less.

### CODE REVIEW

**Review by crozzy — APPROVED** [review]
LGTM, I'd say we're probably good not iterating the version right?

**Comment by hdonnay** [comment]
Yes -- After this change the created packages will have _a_ normalized version populated for the `runtime` package, but it's not used due to the lack of prerelease support for that workflows.

**Comment by hdonnay** [comment]
Decided that urlencoding the whole path was going to be annoying, so I fixed the escaping in `zlog`.

**Review by crozzy — APPROVED** [review]
:+1:

**Pull request merged**
