### PR TITLE
implement migrations

### PR DESCRIPTION
**Pull request by ldelossa**
PR implements migrations which run on library instantiation. 
Migrations must be enabled and are off by default. The bool for flipping this option resides in each library's `Opts` struct.

### CODE REVIEW

**Comment by ldelossa** [comment]
@hdonnay have this as a draft PR. 
Preferably we remove the boostrap.sql files in the implementation directories. Do we need to update the test package to make this work with our test harness?

**Comment by hdonnay** [comment]
Yeah, it'll need to run the migrations.

Does the library do track of what "revision" the database is on and locking of changes?

**Comment by ldelossa** [comment]
@hdonnay 

Yes it does. It creates a defined table name:
https://github.com/quay/claircore/pull/72/files#diff-d47afd42e4850194788d6b3ca3093670R10

and tracks migrations via the migration's id.

**Comment by ldelossa** [comment]
```
diff --git a/internal/indexer/postgres/teststore.go b/internal/indexer/postgres/teststore.go
index a4e4dbc..3ebf269 100644
--- a/internal/indexer/postgres/teststore.go
+++ b/internal/indexer/postgres/teststore.go
@@ -5,10 +5,11 @@ import (
 	"context"
 	"fmt"
 	"os/exec"
-	"path/filepath"
 	"testing"
 
+	"github.com/quay/claircore/libindex/migrations"
 	"github.com/quay/claircore/test/integration"
+	"github.com/remind101/migrate"
 
 	"github.com/jackc/pgx/v4/pgxpool"
 	_ "github.com/jackc/pgx/v4/stdlib" // Needed for sqlx.Open
@@ -23,7 +24,7 @@ func TestStore(ctx context.Context, t testing.TB) (*sqlx.DB, *store, func()) {
 	}
 	o = bytes.TrimSpace(o)
 
-	db, err := integration.NewDB(ctx, t, integration.DefaultDSN, filepath.Join(string(o), "bootstrap.sql"))
+	db, err := integration.NewDB(ctx, t, integration.DefaultDSN)
 	if err != nil {
 		t.Fatalf("unable to create test database: %w", err)
 	}
@@ -42,6 +43,14 @@ func TestStore(ctx context.Context, t testing.TB) (*sqlx.DB, *store, func()) {
 		t.Fatalf("failed to sqlx Open: %v", err)
 	}
 
+	// run migrations
+	migrator := migrate.NewPostgresMigrator(sx.DB)
+	migrator.Table = migrations.MigrationTable
+	err = migrator.Exec(migrate.Up, migrations.Migrations...)
+	if err != nil {
+		t.Fatalf("failed to perform migrations: %w", err)
+	}
+
 	s := NewStore(sx, pool)
 
 	return sx, s, func() {
diff --git a/internal/vulnstore/postgres/testvulnstore.go b/internal/vulnstore/postgres/testvulnstore.go
index 05e6567..f8bbbc8 100644
--- a/internal/vulnstore/postgres/testvulnstore.go
+++ b/internal/vulnstore/postgres/testvulnstore.go
@@ -8,7 +8,9 @@ import (
 	"path/filepath"
 	"testing"
 
+	"github.com/quay/claircore/libvuln/migrations"
 	"github.com/quay/claircore/test/integration"
+	"github.com/remind101/migrate"
 
 	"github.com/jackc/pgx/v4"
 	"github.com/jackc/pgx/v4/log/testingadapter"
@@ -44,6 +46,14 @@ func TestStore(ctx context.Context, t testing.TB) (*sqlx.DB, *Store, func()) {
 		t.Fatalf("failed to sqlx Open: %v", err)
 	}
 
+	// run migrations
+	migrator := migrate.NewPostgresMigrator(sx.DB)
+	migrator.Table = migrations.MigrationTable
+	err = migrator.Exec(migrate.Up, migrations.Migrations...)
+	if err != nil {
+		t.Fatalf("failed to perform migrations: %w", err)
+	}
+
 	s := NewVulnStore(sx, pool)
 
 	return sx, s, func() {
diff --git a/test/integration/db.go b/test/integration/db.go
index 07f9065..c8d7f58 100644
--- a/test/integration/db.go
+++ b/test/integration/db.go
@@ -1,13 +1,11 @@
 package integration
 
 import (
-	"bytes"
 	"context"
 	crand "crypto/rand"
 	"encoding/binary"
 	"fmt"
 	"io"
-	"io/ioutil"
 	"math/rand"
 	"testing"
 
@@ -41,7 +39,7 @@ const (
 )
 
 // NewDB creates a new database and populates it with the contents of initfile.
-func NewDB(ctx context.Context, t testing.TB, dsn, initfile string) (*DB, error) {
+func NewDB(ctx context.Context, t testing.TB, dsn string) (*DB, error) {
 	cfg, err := pgxpool.ParseConfig(dsn)
 	if err != nil {
 		return nil, err
@@ -65,24 +63,8 @@ func NewDB(ctx context.Context, t testing.TB, dsn, initfile string) (*DB, error)
 		return nil, err
 	}
 
-	b, err := ioutil.ReadFile(initfile)
-	if err != nil {
-		return nil, err
-	}
-
 	cfg.ConnConfig.Database = database
 	cfg.ConnConfig.User = role
-	conn, err = pgx.ConnectConfig(ctx, cfg.ConnConfig)
-	if err != nil {
-		return nil, err
-	}
-
-	if _, err := conn.Exec(ctx, bytes.NewBuffer(b).String()); err != nil {
-		return nil, err
-	}
-	if err := conn.Close(ctx); err != nil {
-		return nil, err
-	}
 	t.Logf("config: %+#v", cfg.ConnConfig)
 	cfg.ConnConfig.Logger = nil
 ```

Diff look okay @hdonnay ?

**Pull request merged**
