### PR TITLE
cicd: add go1.22 to CI

### PR DESCRIPTION
**Pull request by hdonnay**

### CODE REVIEW

**Review by crozzy — APPROVED** [review]
LGTM Weird that code coverage would have gone down, it seems like 1.21 and 1.22 would deal with the same code footprint

**Comment by hdonnay** [comment]
Yeah, I'm unsure if it's the go instrumentation changing? I've looked at this a little locally and can't work out why the coverage fluctuates.

**Comment by hdonnay** [comment]
arg, this is merged. GitHub managed to process the push to my fork that happened after the push to origin in the wrong order.

**Pull request closed without merging**
