### PR TITLE
all: update generate directives with run commands

### PR DESCRIPTION
**Pull request by hdonnay**
This change uses `go run` in the generate directives where applicable. The indirect "tool" build tag is removed. This should track dependencies more accurately and has been supported for several go versions.

This means `go generate` should just work everywhere now, without needing any install setup.

### CODE REVIEW

**Review by crozzy — APPROVED** [review]

**Comment by RTann** [comment]
I think I'd prefer keeping this in the `go.mod`, as version bumps only require updating a single file, and it can be updated by dependabot easily.

**Comment by hdonnay** [comment]
> I think I'd prefer keeping this in the `go.mod`, as version bumps only require updating a single file, and it can be updated by dependabot easily.

That's a good point, I think just switching to the `go run` style has the same benefit.

**Comment by hdonnay** [comment]
For more context, this came up because of quay/clair#1696, but I think @RTann is right that the same "version-in-command" solution makes less sense here.

**Comment by hdonnay** [comment]
going to consider @crozzy's approval good enough

**Pull request merged**
