### PR TITLE
etc: add import helper

### PR DESCRIPTION
**Pull request by hdonnay**

### CODE REVIEW

**Review by crozzy — APPROVED** [review]

**Comment by crozzy** [comment]
Do we want to add something like this as discussed:
```yaml
  import-check:
    needs: ['config']
    name: Import Check
    runs-on: ubuntu-latest
    container: quay.io/projectquay/golang:${{ fromJSON(needs.config.outputs.go_versions)[0] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Go Imports
        run: ./etc/importfix.sh
      - name: Git Diff
        run: git diff --exit-code
```

**Comment by hdonnay** [comment]
Do you think that's worth putting in this PR?

**Comment by crozzy** [comment]
It seems like at the moment things are pretty much in line as far as existing code save for two minor formatting issues, do we want to just fix them and then do a full `goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")` every time?

**Comment by hdonnay** [comment]
going to rebase and merge

**Pull request merged**
