### PR TITLE
java: update matching error with vuln name

### PR DESCRIPTION
**Pull request by RTann**
It's hard to debug this when I don't know the vulnerability's name

### CODE REVIEW

**Review by crozzy — APPROVED** [review]

**Comment by RTann** [comment]
Another thing to consider: should we error here or just say it's not vulnerable? Is it worth getting no results vs a false negative for one vuln?

@hdonnay @crozzy

**Comment by crozzy** [comment]
> Another thing to consider: should we error here or just say it's not vulnerable? Is it worth getting no results vs a false negative for one vuln?
> 
> @hdonnay @crozzy

I think this is a far point but in theory I think you would get results just none from that particular matcher (not sure if that's better or worse). Currently, it looks like there is mixture of patterns, I'm leaning towards log and return nil.

**Review by hdonnay — APPROVED** [review]

**Comment by crozzy** [comment]
Is he going to try :fast_forward: ?

**Comment by hdonnay** [comment]
.jpg)

**Pull request merged**
